// <copyright file="GlobalSuppressions.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1652:Enable XML documentation output", Justification = "No need for this rule")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "AirportsFeedReader.Data.NoSqlDatabaseCacheStorage", Justification = "NoSqlQuery")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2100:Review SQL queries for security vulnerabilities", Scope = "member", Target = "AirportsFeedReader.Data.NoSqlDatabaseCacheStorage.", Justification = "Using blocs")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "AirportsFeedReader.Data.NoSqlDatabaseCacheStorage.#SaveDate(System.String,System.String)", Justification = "No need for this rule")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2100:Review SQL queries for security vulnerabilities", Scope = "member", Target = "AirportsFeedReader.Data.NoSqlDatabaseCacheStorage.#SaveDate(System.String,System.String)", Justification = "No need for this rule")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "AirportsFeedReader.Data.NoSqlDatabaseCacheStorage.#ClearData(System.String)", Justification = "No need for this rule")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2100:Review SQL queries for security vulnerabilities", Scope = "member", Target = "AirportsFeedReader.Data.NoSqlDatabaseCacheStorage.#ClearData(System.String)", Justification = "No need for this rule")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "AirportsFeedReader.Data.NoSqlDatabaseCacheStorage.#GetData(System.String)", Justification = "No need for this rule")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2100:Review SQL queries for security vulnerabilities", Scope = "member", Target = "AirportsFeedReader.Data.NoSqlDatabaseCacheStorage.#GetData(System.String)", Justification = "No need for this rule")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2100:Review SQL queries for security vulnerabilities", Scope = "member", Target = "AirportsFeedReader.Data.NoSqlDatabaseCacheStorage.#Initialize()", Justification = "No need for this rule")]